# Pre-commit hooks configuration
# This file ensures code quality and formatting on every commit

repos:
  # Black - Python code formatter (auto-fixes)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py310]
        files: \.py$

  # isort - Import sorting (auto-fixes)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: \.py$

  # General file checks (auto-fixes)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  # Custom requirements validation
  - repo: local
    hooks:
      - id: validate-requirements
        name: Validate requirements.txt
        entry: ./scripts/validate-requirements.py
        language: system
        files: requirements\.txt$
        pass_filenames: false
